version: '2'
services:
  groupexpensetracker-app:
    image: groupexpensetracker
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://groupexpensetracker-mssql:1433;database=GroupExpenseTracker
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8081:8081
  groupexpensetracker-mssql:
    extends:
      file: mssql.yml
      service: groupexpensetracker-mssql
